# Generated by Django 6.0.7 on 2026-07-10 19:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(default='litres', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(blank=True, max_length=100)),
                ('record_id', models.PositiveIntegerField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.product')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumps', to='main.product')),
            ],
            options={
                'ordering': ['product', 'pump_number'],
                'unique_together': {('product', 'pump_number')},
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('cash_submitted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='main.manager')),
            ],
            options={
                'ordering': ['-shift_date', 'shift_type'],
                'unique_together': {('shift_date', 'shift_type')},
            },
        ),
        migrations.CreateModel(
            name='FuelReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres_received', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_receipts', to='main.shift')),
            ],
        ),
        migrations.CreateModel(
            name='TankReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres_returned', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product')),
                ('pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pump')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_returns', to='main.shift')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='main.pump')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='main.shift')),
            ],
            options={
                'unique_together': {('shift', 'pump')},
            },
        ),
        migrations.CreateModel(
            name='TankSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fuel_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fuel_returned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fuel_sold', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_snapshots', to='main.shift')),
            ],
            options={
                'unique_together': {('shift', 'product')},
            },
        ),
    ]
